version: '3.1'
services:
  db:
    image: postgres:12.2-alpine
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=sql_primer_db_role
      - POSTGRES_PASSWORD=primer
      - POSTGRES_DB=sql_primer
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/fixtures.sql:/docker-entrypoint-initdb.d/2-fixtures.sql